# Ordered item list extracted from the first inventory status sheet.

WEEKLY_INVENTORY_ITEMS = [('QWC-Q1500GR', '[리큐엠] QWC-Q1500 무선충전기 그레이'),
 ('QWC-Q1500WH', '[리큐엠] QWC-Q1500 무선충전기 화이트'),
 ('QWC-Q1500-GR-PM', '[리큐엠] QWC-Q1500 무선충전기 그레이-판촉용'),
 ('QWC-Q1500-WH-PM', '[리큐엠] QWC-Q1500 무선충전기 화이트-판촉용'),
 ('QWC-QS1500-BL', '[리큐엠] 무선충전기 QWC-QS1500 블루'),
 ('QWC-QS1500-PK', '[리큐엠] 무선충전기 QWC-QS1500 핑크'),
 ('QWC-QS1500-GR', '[리큐엠] 무선충전기 QWC-QS1500 그린'),
 ('SET-SOMEONE-PINK', 'SOMEONE 무선충전세트 - 핑크'),
 ('SOMEONE-BLUE', 'SOMEONE -블루(DIFUNG)'),
 ('QWC-Q3100S-BK', '[리큐엠] 3in1 무선충전기 Q3100S 블랙 [갤럭시워치]'),
 ('QWC-Q3100S-WH', '[리큐엠] 3in1 무선충전기 Q3100S(갤럭시) 화이트'),
 ('QWC-Q3100S-BK_PM', '[리큐엠] 3in1 무선충전기 Q3100S(갤럭시) 블랙-판촉용'),
 ('QMC-QM4100_GY', '리큐엠 맥세이프 충전기-QM4100_그레이'),
 ('QMC-QM4100_WH', '리큐엠 맥세이프 충전기-QM4100_화이트'),
 ('QMC-ACONE-MB', '리큐엠 맥세이프 무선충전기-ACONE_모닝 브리즈'),
 ('QMC-ACONE-SS', '리큐엠 맥세이프 무선충전기-ACONE_선셋'),
 ('QMC-ACONE-WL', '리큐엠 맥세이프 무선충전기-ACONE_원더랜드'),
 ('QMC-ACONE-MS', '리큐엠 맥세이프 무선충전기-ACONE_미드나잇 섀도우'),
 ('QWC-CW500', '[리큐엠] 차량용무선충전기 QWC-CW500'),
 ('QWC-L5100-A', '[리큐엠] 무선충전기 L5100 애플'),
 ('QWC-L5100-S', '[리큐엠] 무선충전기 L5100 삼성(안드로이드)'),
 ('QMC-T3100_BE', '맥세이프 폴더블 3IN1 무선충전기_베이지'),
 ('QMC-T3100_BK', '맥세이프 폴더블 3IN1 무선충전기_블랙'),
 ('QWC-A1500A', '무선충전기 QWC-A1500A'),
 ('[RQM]-QMP5-WH', '[리큐엠] 맥세이프 무선충전 보조배터리 QMP5 화이트'),
 ('[RQM]-QP1000C1-BK', '[리큐엠] 보조배터리 QP1000C1 블랙'),
 ('[RQM]-QP1000C1-WH', '[리큐엠] 보조배터리 QP1000C1 화이트'),
 ('[RQM]-QP1000C1-BL', '[리큐엠] 보조배터리 QP1000C1 블루'),
 ('[RQM]-QP1000C1-PK', '[리큐엠] 보조배터리 QP1000C1 핑크'),
 ('QP1000C1-Butter', '[리큐엠] 보조배터리 QP1000C1 버터'),
 ('QP1000C1-Carrot', '[리큐엠] 보조배터리 QP1000C1 캐롯'),
 ('QP1000C1-NeonGreen', '[리큐엠] 보조배터리 QP1000C1 네온그린'),
 ('QP1000C1-CobaltBlue', '[리큐엠] 보조배터리 QP1000C1 코발트블루'),
 ('[RQM]-QP2000C1-BK', '[리큐엠] QP2000C 블랙'),
 ('[RQM]-QP2000C1-WH', '[리큐엠] QP2000C 화이트'),
 ('[RQM]-QP2000C1-Beige', '[리큐엠] QP2000C 베이지'),
 ('[RQM]-QP2000C1-Green', '[리큐엠] QP2000C 그린'),
 ('QP2000C_SageMint', 'QP2000C_세이지민트'),
 ('QP2000C_TomatoRed', 'QP2000C_토마토레드'),
 ('[RQM]QP2000A(CP)-BK', '[리큐엠] QP2000A(CP) 블랙'),
 ('SP-일체형8핀', '[SOMOON]5,000mAh 일체형 보조배터리_A8'),
 ('SP-AC50-공용8핀', '[SOMOON]5,000mAh 일체형 보조배터리(공용)_AC50'),
 ('QS-QST01M_BK', '리큐엠 셀카봉-QST01M미니_블랙'),
 ('QS-QST01M_WH', '리큐엠 셀카봉-QST01M미니_화이트'),
 ('QMS-QMS01_BK', '리큐엠 맥세이프 셀카봉-QMS01_블랙'),
 ('QPD-330_SGY', '리큐엠 가정용 충전기-QPD-330_솔리드그레이'),
 ('QPD-330_WH', '리큐엠 가정용 충전기-QPD-330_화이트'),
 ('QPD-330_BL', '리큐엠 가정용 충전기-QPD-330_블루'),
 ('QPD-330_PK', '리큐엠 가정용 충전기-QPD-330_핑크'),
 ('QPD-365N_GY', '리큐엠 가정용 충전기-QPD-365N_그레이'),
 ('QPD-365N_WH', '리큐엠 가정용 충전기-QPD-365N_화이트'),
 ('QPD-365NP_GY', '리큐엠 가정용 충전기-QPD-365NP_그레이'),
 ('QPD-365NP_WH', '리큐엠 가정용 충전기-QPD-365NP_화이트'),
 ('QTC-45W_BK', '리큐엠 45W 여행용 충전기_블랙'),
 ('QTC-45W_WH', '리큐엠 45W 여행용 충전기_화이트'),
 ('RQM-CC150-CK-BL', '[리큐엠]C.class K-CC150-실리콘케이블 블루(100W)'),
 ('RQM-CC150-CK-PK', '[리큐엠]C.class K-CC150-실리콘케이블 핑크(100W)'),
 ('RQM-MFICA150-CS', '[리큐엠]MFI-CA150-실리콘케이블 화이트(60W) [1.5M]'),
 ('QCB-CC30S_Butter', '리큐엠 케이블-CC30S_버터'),
 ('QCB-CC30S_Carrot', '리큐엠 케이블-CC30S_캐롯'),
 ('QCB-CC30S_CobaltBlue', '리큐엠 케이블-CC30S_코발트블루'),
 ('QCB-CC30S_NeonGreen', '리큐엠 케이블-CC30S_네온그린'),
 ('QCB-CC30S_Lavender', '리큐엠 케이블-CC30S_라벤더'),
 ('QCB-CC60S_Butter', '리큐엠 케이블-CC60S_버터'),
 ('QCB-CC60S_Carrot', '리큐엠 케이블-CC60S_캐롯'),
 ('QCB-CC60S_CobaltBlue', '리큐엠 케이블-CC60S_코발트블루'),
 ('QCB-CC60S_NeonGreen', '리큐엠 케이블-CC60S_네온그린'),
 ('QCB-CC60S_Lavender', '리큐엠 케이블-CC60S_라벤더'),
 ('QWC-UV300-BK', '리큐엠-UV살균기 무선충전 시계_블랙'),
 ('VAUX-QCL100-레드', 'VAUX_캠핑용 랜턴 QCL100_레드'),
 ('VAUX-QCL100-블랙', 'VAUX_캠핑용 랜턴 QCL100 블랙'),
 ('VAUX-QCL100-블루', 'VAUX_캠핑용 랜턴 QCL100_블루'),
 ('VAUX-QCL100-샌드', 'VAUX_캠핑용 랜턴 QCL100_샌드'),
 ('VAUX-QCL100-화이트', 'VAUX_캠핑용 랜턴 QCL100 화이트'),
 ('ACONE-Sliconpad_SA', 'ACONE-실리콘패드_샌드'),
 ('ACONE-Sliconpad_BK', 'ACONE-실리콘패드_블랙'),
 ('ACONE-Sliconpad_RD', 'ACONE-실리콘패드_레드'),
 ('ACONE-Sliconpad_MU', 'ACONE-실리콘패드_머스타드'),
 ('ACONE-Sliconpad_CO', 'ACONE-실리콘패드_코랄'),
 ('ACONE-Sliconpad_CL', 'ACONE-실리콘패드_클라우드'),
 ('QA-Luggagescale_BK', '리큐엠 액세서리-캐리어저울_블랙'),
 ('QA-Luggagescale_WH', '리큐엠 액세서리-캐리어저울_화이트'),
 ('QA-Custumpouch_BK', '리큐엠 액세서리-커스텀파우치_블랙'),
 ('QA-Custumpouch_BL', '리큐엠 액세서리-커스텀파우치_블루'),
 ('QA-Custumpouch_GR', '리큐엠 액세서리-커스텀파우치_그린'),
 ('QA-Custumpouch_BE', '리큐엠 액세서리-커스텀파우치_베이지'),
 ('QA-Custumpouch_YL', '리큐엠 액세서리-커스텀파우치_옐로우'),
 ('QA-Minihardpouch_BK', '리큐엠 액세서리-미니하드파우치_블랙'),
 ('QA-Minihardpouch_BE', '리큐엠 액세서리-미니하드파우치_베이지'),
 ('QA-Minihardpouch_BL', '리큐엠 액세서리-미니하드파우치_블루'),
 ('QA-Minihardpouch_GR', '리큐엠 액세서리-미니하드파우치_그린'),
 ('QA-Minihardpouch_YL', '리큐엠 액세서리-미니하드파우치_옐로우'),
 ('QA-KeyRing_R', '리큐엠 액세서리-키링_R'),
 ('QA-KeyRing_E', '리큐엠 액세서리-키링_E'),
 ('QA-KeyRing_Q', '리큐엠 액세서리-키링_Q'),
 ('QA-KeyRing_M', '리큐엠 액세서리-키링_M'),
 ('QA-Jibbitz_GOOUT', '리큐엠 액세서리-지비츠_GO OUT'),
 ('QA-Jibbitz_CAMPING', '리큐엠 액세서리-지비츠_CAMPING'),
 ('QA-Jibbitz_TRAVEL', '리큐엠 액세서리-지비츠_TRAVEL'),
 ('QA-Jibbitz_SPORTS', '리큐엠 액세서리-지비츠_SPORTS'),
 ('QA-Rug_GOOUT_RD', '리큐엠 액세서리-Rug_GOOUT_레드'),
 ('QA-Rug_GOOUT_YL', '리큐엠 액세서리-Rug_GOOUT_옐로우'),
 ('QA-Rug_GOOUT_GR', '리큐엠 액세서리-Rug_GOOUT_그린'),
 ('QA-Rug_GOOUT_BL', '리큐엠 액세서리-Rug_GOOUT_블루'),
 ('QA-Rug_SYMBOL-B_BL', '리큐엠 액세서리-Rug_SYMBOL-B_블루'),
 ('POUCH-Tarpaulin-BK', '타포린 파우치_블랙'),
 ('POUCH-Tarpaulin-BLUE', '타포린 파우치_블루'),
 ('POUCH-Tarpaulin-RED', '타포린 파우치_레드'),
 ('POUCH-Tarpaulin-WH', '타포린 파우치_화이트'),
 ('POUCH-Tarpaulin-YL', '타포린 파우치_옐로우'),
 ('POUCH-Tarpaulin_F-GR', '타포린 파우치_그레이'),
 ('CASE-QP1000A-Ebony', 'QP1000 실리콘 케이스_에보니'),
 ('CASE-QP1000A-Lavende', 'QP1000 실리콘 케이스_라벤더'),
 ('CASE-QP1000A-Mint', 'QP1000 실리콘 케이스_민트'),
 ('CASE-QP1000A-Sand', 'QP1000 실리콘 케이스_샌드'),
 ('CASE-QP1000-Cl-kyobo', 'QP1000 실리콘 케이스_투명_교보용'),
 ('CASE-QP1000C-Hand-Bl', 'QP1000 실리콘 케이스_핸디형_블루'),
 ('CASE-QP1000C-Hand-Cl', 'QP1000 실리콘 케이스_핸디형_클라우드'),
 ('CASE-QP1000C-Hand-Eb', 'QP1000 실리콘 케이스_핸디형_에보니'),
 ('CASE-QP1000C-Hand-Gr', 'QP1000 실리콘 케이스_핸디형_그린'),
 ('CASE-QP1000C-Hand-La', 'QP1000 실리콘 케이스_핸디형_라벤더'),
 ('CASE-QP1000C-Hand-Mi', 'QP1000 실리콘 케이스_핸디형_민트'),
 ('CASE-QP1000C-Hand-Re', 'QP1000 실리콘 케이스_핸디형_레드'),
 ('CASE-QP1000C-Hand-Sa', 'QP1000 실리콘 케이스_핸디형_샌드'),
 ('CASE-QP1000C-Hand-PK', 'QP1000 실리콘 케이스_핸디형_핑크'),
 ('CASE-QP1000C-Hand-Ye', 'QP1000 실리콘 케이스_핸디형_옐로우'),
 ('CASE-QP1000-Hand-GlB', 'QP1000 실리콘 케이스_핸디형_글로우 블루'),
 ('CASE-QP1000-Hand-GlG', 'QP1000 실리콘 케이스_핸디형_글로우 그린'),
 ('CASE-QP1000-Hand-GlO', 'QP1000 실리콘 케이스_핸디형_글로우 오렌지'),
 ('CASE-QP1000-Hand-GlY', 'QP1000 실리콘 케이스_핸디형_글로우 옐로우'),
 ('CASE-QP2000C-Blue', 'QP2000 실리콘 케이스_블루'),
 ('CASE-QP2000C-Cloud', 'QP2000 실리콘 케이스_클라우드'),
 ('CASE-QP2000C-Ebony', 'QP2000 실리콘 케이스_에보니'),
 ('CASE-QP2000C-Green', 'QP2000 실리콘 케이스_그린'),
 ('CASE-QP2000C-Lavende', 'QP2000 실리콘 케이스_라벤더'),
 ('CASE-QP2000C-Mint', 'QP2000 실리콘 케이스_민트'),
 ('CASE-QP2000C-Red', 'QP2000 실리콘 케이스_레드'),
 ('CASE-QP2000C-Sand', 'QP2000 실리콘 케이스_샌드'),
 ('CASE-QP2000C-PINK', 'QP2000 실리콘 케이스_핑크'),
 ('CASE-QP2000C-Yellow', 'QP2000 실리콘 케이스_옐로우'),
 ('CASE-QP2000-Cl-kyobo', 'QP2000 실리콘 케이스_투명_교보용'),
 ('CASE-QP2000C_Hand_La', 'QP2000C 실리콘 케이스 핸디형 라벤더'),
 ('CASE-QP2000C_Hand_Mi', 'QP2000C 실리콘 케이스 핸디형 민트'),
 ('CASE-QP2000C_Hand_Sa', 'QP2000C 실리콘 케이스 핸디형 샌드'),
 ('CASE-QP2000C_Hand_PK', 'QP2000C 실리콘 케이스 핸디형 핑크'),
 ('CASE-QP2000-Hand-GlB', 'QP2000 실리콘 케이스_핸디형_글로우 블루'),
 ('CASE-QP2000-Hand-GlG', 'QP2000 실리콘 케이스_핸디형_글로우 그린'),
 ('CASE-QP2000-Hand-GlO', 'QP2000 실리콘 케이스_핸디형_글로우 오렌지'),
 ('CASE-QP2000-Hand-GlY', 'QP2000 실리콘 케이스_핸디형_글로우 옐로우'),
 ('QMA-Cardwallet_BR', '리큐엠 맥세이프 액세서리-카드지갑_브라운'),
 ('QMA-Cardwallet_OR', '리큐엠 맥세이프 액세서리-카드지갑_오렌지'),
 ('QMA-Cardwallet_GR', '리큐엠 맥세이프 액세서리-카드지갑_그린'),
 ('QMA-Cardwallet_NA', '리큐엠 맥세이프 액세서리-카드지갑_네이비'),
 ('QMA-Cardwallet_PK', '리큐엠 맥세이프 액세서리-카드지갑_핑크'),
 ('QMA-Cardwallet_BE', '리큐엠 맥세이프 액세서리-카드지갑_베이지'),
 ('QMA-Cardwallet_DBR', '리큐엠 맥세이프 액세서리-카드지갑_다크브라운'),
 ('QMA-Cardwallet_SGY', '리큐엠 맥세이프 액세서리-카드지갑_솔리드그레이'),
 ('QMA-Cardwallet_AGY', '리큐엠 맥세이프 액세서리-카드지갑_애쉬그레이'),
 ('QMA-Ringsticker_BK', '리큐엠 맥세이프 액세서리-링스티커_블랙'),
 ('QMA-Bubblepad_Or', '리큐엠 맥세이프 액세서리-버블패드_소프트 오렌지'),
 ('QMA-Bubblepad_La', '리큐엠 맥세이프 액세서리-버블패드_소프트 라벤더'),
 ('QMA-Bubblepad_Mi', '리큐엠 맥세이프 액세서리-버블패드_소프트 민트'),
 ('QMA-Bubblepad_Bl', '리큐엠 맥세이프 액세서리-버블패드_소프트 블루'),
 ('QMA-Bubblepad_Bk', '리큐엠 맥세이프 액세서리-버블패드_소프트 블랙'),
 ('QMA-Bubblepad-Cr', '리큐엠 맥세이프 액세서리-버블패드_소프트 크림')]
