create table if not exists public.cs_cases (
  id uuid primary key default gen_random_uuid(),
  channel text not null check (channel in ('product_qna', 'order_inquiry')),
  external_id text not null,
  question text not null default '',
  product_order_id text,
  product_no text,
  product_model text,
  category text,
  risk_level text not null default 'normal',
  status text not null default 'unanswered',
  assignee_id uuid references auth.users(id),
  source_created_at timestamptz,
  collected_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (channel, external_id)
);

create table if not exists public.cs_drafts (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.cs_cases(id) on delete cascade,
  operator_note text not null default '',
  generated_draft text not null default '',
  final_answer text not null default '',
  knowledge_refs jsonb not null default '[]'::jsonb,
  version integer not null default 1 check (version > 0),
  status text not null default 'draft',
  created_by uuid not null default auth.uid() references auth.users(id),
  updated_by uuid not null default auth.uid() references auth.users(id),
  approved_by uuid references auth.users(id),
  sent_by uuid references auth.users(id),
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (case_id, version)
);

create table if not exists public.cs_audit_logs (
  id bigint generated by default as identity primary key,
  case_id uuid references public.cs_cases(id) on delete cascade,
  draft_id uuid references public.cs_drafts(id) on delete set null,
  action text not null,
  actor_id uuid not null default auth.uid() references auth.users(id),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists cs_cases_status_updated_idx on public.cs_cases (status, updated_at desc);
create index if not exists cs_cases_assignee_idx on public.cs_cases (assignee_id, status);
create index if not exists cs_drafts_case_updated_idx on public.cs_drafts (case_id, updated_at desc);
create index if not exists cs_audit_case_created_idx on public.cs_audit_logs (case_id, created_at desc);

alter table public.cs_cases enable row level security;
alter table public.cs_drafts enable row level security;
alter table public.cs_audit_logs enable row level security;

drop policy if exists "authenticated users read cs cases" on public.cs_cases;
create policy "authenticated users read cs cases" on public.cs_cases
  for select to authenticated using (true);
drop policy if exists "authenticated users write cs cases" on public.cs_cases;
create policy "authenticated users write cs cases" on public.cs_cases
  for all to authenticated using (true) with check (true);

drop policy if exists "authenticated users read cs drafts" on public.cs_drafts;
create policy "authenticated users read cs drafts" on public.cs_drafts
  for select to authenticated using (true);
drop policy if exists "authenticated users write cs drafts" on public.cs_drafts;
create policy "authenticated users write cs drafts" on public.cs_drafts
  for all to authenticated using (true) with check (true);

drop policy if exists "authenticated users read cs audit logs" on public.cs_audit_logs;
create policy "authenticated users read cs audit logs" on public.cs_audit_logs
  for select to authenticated using (true);
drop policy if exists "authenticated users append cs audit logs" on public.cs_audit_logs;
create policy "authenticated users append cs audit logs" on public.cs_audit_logs
  for insert to authenticated with check (actor_id = auth.uid());

grant select, insert, update, delete on public.cs_cases to authenticated;
grant select, insert, update, delete on public.cs_drafts to authenticated;
grant select, insert on public.cs_audit_logs to authenticated;
grant usage, select on sequence public.cs_audit_logs_id_seq to authenticated;
